### ISSUE TITLE
People fields

### ISSUE THREAD

**Issue by fanatid** [keithamus/sort-package-json#105]
[people fields](https://docs.npmjs.com/files/package.json#people-fields-author-contributors) include not only `author`, but `contributors` too.

Currently, only author in list:
https://github.com/keithamus/sort-package-json/blob/2108c5ade72463a6786b4408ea1dccbcaa6541fa/index.js#L73

**Comment by fisker** [comment]
missed on a code refactor, https://github.com/keithamus/sort-package-json/pull/90

**Comment by fanatid** [comment]
Thank you!
