### ISSUE TITLE
feature request: don't change already sorted package.json

### ISSUE THREAD

**Issue by agirorn** [keithamus/sort-package-json#11]
When running sort-package-json twice should only update the file once. Then I can run this everytime the package.json file changes and that way keep the package.json file forever sorted. What happens now is that running sort-package-json saves a new file every time and triggers the watchers to rerun the task that is watching package.json.

**Comment by keithamus** [comment]
Great idea! Would you like to make a PR for this?

**Comment by agirorn** [comment]
sure.

**Comment by agirorn** [comment]
feat: only sort unsorted package.json file #14

**Comment by keithamus** [comment]
Should be `1.6.0` https://travis-ci.org/keithamus/sort-package-json/builds/218626314
