### ISSUE TITLE
Sorting right after npm init

### ISSUE THREAD

**Issue by MiniGod** [keithamus/sort-package-json#13]
Is there any particular reason for the order of which the keys are sorted?

For instance, why isn't a `package.json` that comes out of `npm init` considered sorted?

```diff
--- original-package.json	2017-03-30 14:13:27.363116322 +0000
+++ sorted-package.json		2017-03-30 14:13:29.727094856 +0000
@@ -1,11 +1,11 @@
 {
   "name": "sort-test",
   "version": "1.0.0",
   "description": "",
+  "license": "ISC",
+  "author": "",
   "main": "index.js",
   "scripts": {
     "test": "echo \"Error: no test specified\" && exit 1"
-  },
-  "author": "",
-  "license": "ISC"
+  }
 }
```

**Comment by keithamus** [comment]
No particular reason, other than trying to put the most relevant info for users of the package upfront. `license` is very relevant to the user and so should go to the top of the file ("above the fold" if you will), as is author.

**Comment by MiniGod** [comment]
That makes sense. Shouldn't then `engines` be "above the fold" as well?

**Comment by MiniGod** [comment]
I don't mean to question every key here.
You've answered my question so you can close this whenever you'd like.

**Comment by keithamus** [comment]
`engines` is probably worth being above the fold too, yes.

As [the readme says](https://github.com/keithamus/sort-package-json#how-does-it-sort) initially it sets the order to [how the docs are ordered](https://docs.npmjs.com/files/package.json). If you feel strongly about changing the order for a particular reason, I would welcome PRs 😄
