### ISSUE TITLE
[Feature Request] sort "peerDependenciesMeta"

### ISSUE THREAD

**Issue by RebeccaStevens** [keithamus/sort-package-json#141]
Probably best to sort the key so that it directly follows "peerDependencies".

About `peerDependenciesMeta`:
[yarn docs](https://yarnpkg.com/en/docs/package-json#toc-peerdependenciesmeta)
[pnpm docs](https://pnpm.js.org/en/package_json#peerdependenciesmeta)

**Comment by fisker** [comment]
working on it.

**Comment by viceice** [comment]
this probably broken yarn v3 😕

- #301
