### ISSUE TITLE
Files are not sorted

### ISSUE THREAD

**Issue by remcohaszing** [keithamus/sort-package-json#166]
The top level `files` array is filteres by uniqueness. I think this can also be sorted alphabetically.

**Comment by keithamus** [comment]
Hey @remcohaszing thanks for the issue!

Currently it's not sorted alphabetically because there's value to the order of files. For (a contrived) example one might want to have `index.js` at the top of the list, while `extensions.js` appears below that.

**Comment by remcohaszing** [comment]
Thanks for your awesome package! :smile: 

Probably a better example of why the order of files matters is negated globs. I didn’t think of this before.

```json
[
  "lib",
  "!lib/foo"
]
```
