### ISSUE TITLE
move 'private' to top

### ISSUE THREAD

**Issue by mriehema** [keithamus/sort-package-json#17]
As in the most package.json files, 'private' is an important information, which should be below name/version. Could you change this? Do you want an pull-request for this change?

**Comment by keithamus** [comment]
Sure, feel free to raise a PR for this 😄

**Comment by mriehema** [comment]
Awesome, thx.

**Comment by keithamus** [comment]
`1.7.1` btw 😄 https://www.npmjs.com/package/sort-package-json
