### ISSUE TITLE
Add https://www.npmjs.com/package/npm-package-json-lint

### ISSUE THREAD

**Issue by ntwb** [keithamus/sort-package-json#174]
Hey, it would be great if support could be added for `npmpackagejsonlint`

> https://www.npmjs.com/package/npm-package-json-lint

As at the time of writing it has `15,959` weekly downloads

Happy to take a shot at a PR if you I can get some basic pointers or a previous PR for reference...

Thanks for your consideration...

**Comment by keithamus** [comment]
Here's a list of where all of the keys for sorting reside: https://github.com/keithamus/sort-package-json/blob/e77236c73f6dea8b9c36eb6ca42193e300bf34c2/index.js#L169-L271.

You may want to sort the sub-object, which we do for some keys, e.g. https://github.com/keithamus/sort-package-json/blob/e77236c73f6dea8b9c36eb6ca42193e300bf34c2/index.js#L212-L221
