### ISSUE TITLE
Leave conditional exports alone

### ISSUE THREAD

**Issue by dandv** [keithamus/sort-package-json#197]
https://nodejs.org/api/esm.html#esm_conditional_exports states

> Within the "exports" object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. *The general rule is that conditions should be from most specific to least specific in object order.*

I found that `default` was sorted before `node`.

**Comment by fisker** [comment]
You can fix it by removing this `over` from [here](https://github.com/keithamus/sort-package-json/blob/093a4ef2403b52c0a260601553623779fcc70f60/index.js#L191)

**Comment by Xunnamius** [comment]
Just got bitten by this. This makes it hard to use this package in automated publish workflow. Any plan on a fix?

**Comment by Xunnamius** [comment]
@keithamus Sent! Not sure if I need to add any unit tests to it, let me know.

I've been using `npx Xunnamius/sort-package-json` without issue for half a day now :)
