### ISSUE TITLE
`maintainers` should immediately follow `author`

### ISSUE THREAD

**Issue by fregante** [keithamus/sort-package-json#198]
`maintainers` was moved to the bottom of the file. I think they should immediately follow `author` as they're part of the same idea.

https://docs.npmjs.com/configuring-npm/package-json.html#people-fields-author-contributors

> The “author” is one person. “contributors” is an array of people.
> npm also sets a top-level “maintainers” field with your npm user info.

The order I think should be:

1. author
2. maintainers
3. contributors

**Comment by keithamus** [comment]
PRs welcome!
