### ISSUE TITLE
Defective under yarn2 with pnp

### ISSUE THREAD

**Issue by leaumar** [keithamus/sort-package-json#205]
My package.json is no longer sorted by prettier with this plugin after upgrading to yarn2 and enabling pnp (neither via IDE plugin nor via independent CLI). Setting `nodeLinker: node-modules` in yarn2 makes the sorting work again. Relevant info for the plugin dev: https://yarnpkg.com/features/pnp

Reproduction steps:
- create a (take any...) basic repo with yarn classic and this plugin
- `yarn set version berry` & `yarn install`
- change an indent and reorder a script in package.json
- run prettier and observe that the indent is fixed but the script order is not

**Comment by fisker** [comment]
You must using a prettier plugin, not directly using sort-package-json.
This is a prettier issue, it can't detect plugin in yarn pnp.
You can use `prettier --plugin=YOU_PLUGIN_NAME`, or use `{plugins: [YOU_PLUGIN_NAME]}` in your config.

**Comment by leaumar** [comment]
Oh right, sorry, I got the repos mixed up. Thanks for the insight though.

--
Marnick "with ck, 2 capitals, and an apostrophe" L'Eau
