### ISSUE TITLE
Script not sorting in 1.49.0

### ISSUE THREAD

**Issue by Cryptically** [keithamus/sort-package-json#220]
Pacakge.json scripts prop does not get sorted at all.

e.g remains the same order

```
{
   "scripts": {
        "b": "b",
        "a": "a"
   }
}
```

**Comment by joemaller** [comment]
This change was introduced in 1.49 here: https://github.com/keithamus/sort-package-json/pull/206

It was pretty much a breaking change for us, so we've version-locked to 1.48 like this: `npx sort-package-json@1.48`

I'd really like to see script-sorting return behind a flag, similar to how `--check` was implemented.

**Comment by G-Rath** [comment]
I'd actually prefer script sorting to be restored to its original behaviour, and then have the opting out as a flag, since the behaviour it was "fixing" is about a specific subset of users (i.e those that implicitly rely on scripts being in a specific order) rather than all users of this tool.

If I understand the original issue, it also shouldn't be hard to solve:

```
{
  "scripts": {
    "build:ts": "tsc",
    "build:cdk": "cdk synth",
    "build:in-order:1": "npm run build:ts",
    "build:in-order:2": "npm run build:cdk",
    "build": "run-s build:in-order:*"
  }
}
```

**Comment by Maxim-Mazurok** [comment]
> It was pretty much a breaking change for us, so we've version-locked to 1.48 like this: `npx sort-package-json@1.48`

This doesn't work for me, because I have `prettier-plugin-packagejson` installed, and npx picks up locally installed dependency, reported this npx bug here: https://github.com/npm/cli/issues/3776

So, for me scripts look like this:
```
"presort": "npx -y rimraf node_modules",
"sort": "npx -y sort-package-json@1.48",
"aftersort": "npm ci",
```
or, combined: `"sort": "npx -y rimraf node_modules && npx -y sort-package-json@1.48 && npm ci"`

**Comment by keithamus** [comment]
> If I understand the original issue, it also shouldn't be hard to solve:

Please do submit a PR if you think this is solvable in a deterministic and non-configurable way that addresses the concerns of folks like @jonathanmorley.

**Comment by G-Rath** [comment]
@keithamus not sure what pr you're expecting other than a revert: the original sorting was deterministic, and so the "fix" is for the affected users to name their scripts specifically so that the determined order fits with their desired order.

**Comment by G-Rath** [comment]
> adding a heuristic to determine if we should sort scripts or not

I'm happy to do that PR if you wouldn't mind giving me some pointers on a good pattern to use for passing the package json to the script sort method is (currently I'm trying to get it passed into all the functions a la how Array methods pass the whole array as the third argument, but not having a lot of luck).

**Comment by lvoliveira** [comment]
How can I have the scrips sorted even if the `npm-run-all` is in the dependencies? I use `npm-run-all` for other purposes, and I don't care about the order of the scripts, I just want it to be uniquely defined (sorted). Is there any way to disable this behavior? 
(Also, I thought this was a bug. This is not how the [scripts sort documentation](https://github.com/keithamus/sort-package-json/blob/HEAD/defaultRules.md#scripts) states it works.)

**Comment by Maxim-Mazurok** [comment]
> How can I have the scrips sorted even if the `npm-run-all` is in the dependencies? I use `npm-run-all` for other purposes and I don't care about the order of the scripts, I just want it to be uniquely defined (sorted). Is there any way to disable this behavior? (Also, I thought this was a bug. This is not how the [documentation for scripts sort](https://github.com/keithamus/sort-package-json/blob/HEAD/defaultRules.md?rgh-link-date=2021-11-10T16%3A55%3A34Z#scripts) states it works.)

I believe you can make it a non-dev dependency, or use it via npx.
