### ISSUE TITLE
globby v12

### ISSUE THREAD

**Issue by kachkaev** [keithamus/sort-package-json#227]
`globby` v12 got released recently: 
https://github.com/sindresorhus/globby/releases/tag/v12.0.0

It’s used in [`cli.js`](https://github.com/keithamus/sort-package-json/blob/9b76ec173288da0844b975191955f9ee661c50ec/cli.js#L3) and is therefore [listed as a project dependency in `package.json`](https://github.com/keithamus/sort-package-json/blob/0f1c9565cf58e6a2dd0b462759f19068422f4f5e/package.json#L77).

Downstream projects with `globby` v11 or v12 end up with duplicate package instance, which would be nice to fix. As of today, [`globby` v10](https://www.npmjs.com/package/globby/v/10.0.0) is two years old (2019-06-29).

To upgrade `globby` to v12, it will be necessary to replace `require` with `import`, which will make Node 12.20 the minimum supported version for `sort-package-json`. Given this breaking change, maybe there is a window of opportunities to make other updates too?

Happy to help if needed!

**Comment by fisker** [comment]
https://github.com/keithamus/sort-package-json/pull/187

**Comment by keithamus** [comment]
PRs welcome!
