### ISSUE TITLE
[Feature request] Sort only specified sections

### ISSUE THREAD

**Issue by AlekhyaYalla** [keithamus/sort-package-json#246]
sort only specified sections like "dependencies", "devDependencies" etc instead of all the sections. 
It would be more flexible to sort desired sections instead of sorting the whole JSON. 

Thanks!

**Comment by keithamus** [comment]
See https://github.com/keithamus/sort-package-json/blob/master/README.md#i-would-like-this-tool-to-be-configurable-with-a-config-file-or-command-line-arguments
