### ISSUE TITLE
v1.56.0 introduces breaking changes due dependency updates

### ISSUE THREAD

**Issue by garth** [keithamus/sort-package-json#258]
It looks like some of the dependencies which had their major versions updated in the v1.56.0 release might have changed their builds to be ESM only.

Had to revert back to 1.55.0 to fix remix-run which depends on this package.

Dependencies in v1.56.0 should probably be reverted to fix the v1 branch and released as v1.57.0. Then the 1.56.0 changes could be re-release as v2?

**Comment by zuimeidamowang** [comment]
![0zm3z120009fw0o1q4101_W_540_0](https://user-images.githubusercontent.com/72732008/166152842-ef934851-8c5f-4ed1-b312-a96993b535f2.png)
the same error

**Comment by keithamus** [comment]
Should be fixed in v1.56.1. Thanks all for letting me know!
