### ISSUE TITLE
Use natural sorting

### ISSUE THREAD

**Issue by faustbrian** [keithamus/sort-package-json#261]
Hey, would you accept a PR to use natural sorting for dependencies? Currently the sorting seems a bit off for packages that end with numbers.

**Actual**
```json
"devDependencies": {
    "@scope/abc1": "workspace:*",
    "@scope/abc18": "workspace:*",
    "@scope/abc2": "workspace:*",
    "@scope/abc5": "workspace:*",
    "@scope/abc53": "workspace:*",
    "@scope/abc6": "workspace:*",
    "@scope/abc7": "workspace:*"
}
```

**Expected**
```json
"devDependencies": {
    "@scope/abc1": "workspace:*",
    "@scope/abc2": "workspace:*",
    "@scope/abc5": "workspace:*",
    "@scope/abc6": "workspace:*",
    "@scope/abc7": "workspace:*",
    "@scope/abc18": "workspace:*",
    "@scope/abc53": "workspace:*"
}
```

**Comment by keithamus** [comment]
Yep I think that's a great idea!

**Comment by keithamus** [comment]
I'll leave that up to your good judgment 😜

**Comment by danielpza** [comment]
Heads up some package manager sort the fields in the dependencies, I've observed this with `yarn` after running `yarn install.` So it might not be a good idea to sort them if it won't be compatible with the package managers
