### ISSUE TITLE
feature: stdin / stdout

### ISSUE THREAD

**Issue by tomdavidson** [keithamus/sort-package-json#293]
Hello, I have wanted to used sort-package-json  with dprint which handles the file io and needs stdin and standout, such as:
`$ cat package.json | sort-pakcage-json - > package.json`

Would this be beneficial in other contexts?

**Comment by keithamus** [comment]
I like the idea. PRs welcome :slightly_smiling_face:

**Comment by kachkaev** [comment]
👋 @tomdavidson, have you managed to get `sort-pakcage-json` working with `dprint`? Playing around with `dprint` and am curious what an integration would look like.
