### ISSUE TITLE
Support additional keys

### ISSUE THREAD

**Issue by jdcrensh** [keithamus/sort-package-json#30]
Some commonly used keys are missing from the predetermined sorting, and end up getting placed at the bottom of the package.json. Here are a few found in some of the repos I work with:

Somewhere before `scripts`(?):
* `workspaces` (yarn)

Between `scripts` and `dependencies`:
* `proxy` (create-react-app)
* `nodemonConfig`
* `lint-staged`

Side note: Perhaps anything not listed in the predetermined list of keys should appear between `scripts` and `dependencies` instead of at the end? It could simplify your list when it comes to 3rd-party tooling.

**Comment by keithamus** [comment]
Thanks for the issue @jdcrensh 

Im happy to add any number of keys inbetween `scripts` and `dependencies` - including the 4 you mention; but regarding your side note- I'd like to avoid moving _any_ keys above dependencies. Specifically for a few projects I'm working on we have config keys that are very large and I'd like to leave them _below_ dependencies. 

PRs welcome for any keys you'd like to see sorted!

**Comment by keithamus** [comment]
I am very much against this tool having any kind of config at all. I'm more than happy to continue to accept more PRs that add keys (ad infinitum) but I will not accept a PR that introduces configuration. It should be portable and reliable to the point that if I run `npx sort-package-json` on _any_ folder, I can predict the result without looking at files other than package.json

**Comment by raphinesse** [comment]
@keithamus That's a pity. I get your point. However, I don't believe there's a sensible ordering to rule them all.

Would the ability to opt in/out of config usage with a command line switch change anything for you?

**Comment by keithamus** [comment]
@raphinesse I dont think so. I'd also like to keep this tool very simple. Think of it like `gofmt`. It just does what it does - you don't get to pick; but thats a good thing because it alleviates you from _any kind of decision_.

Let's keep in mind the intent behind sorting a package.json is to keep it readable - to keep things in predictable places, so I as a developer can move from one package to the next, and read through the package.json knowing "dependencies goes below scripts". If all of a sudden someone out there decides to create a custom config to sort scripts below dependencies - well, the contract is broken, suddenly the intent of the tool is invalidated, and you may as well not run it at all.

**Comment by unional** [comment]
Just adding my two cents. There might be cases where it really does not have a sensible way to order keys in a certain order.
One example is when the same key is used in two different contexts.

e.g. for one tool, it has:

```js
{
  "a": ...,
  "b": ...,
  "x": ...,
  "y": ...
}
```
while another tool has:
```js
{
  "b": ...,
  "p": ...,
  "y": ...
}
```

In the order, we can enforce it as:

```js
var sortOrder = [
  "a",
  "b",
  "p",
  "x",
  "y"]
```

But once the alphabetic nature of this break (to make it more readable), this would break.

Another issue is that will make the `sortOrder` quite messy to maintain.
🌷

**Comment by gillesdandrea** [comment]
I found a quite common list of properties documented at https://github.com/stereobooster/package.json that could be used for additional properties.

**Comment by keithamus** [comment]
I'll close this issue, as most of the keys mentioned are now sorted. If you would like more keys to be sorted, please feel free to file a PR or an issue! Thanks!
