### ISSUE TITLE
Document the order of top-level keys?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [keithamus/sort-package-json#306]
Is the actual order of keys enforced by this package mentioned in any docs? Sorry if I missed it!

https://github.com/keithamus/sort-package-json/blob/93a1cbcfbc3b7cacd8a93784c61d3b8db8fa23be/index.js#L186 looks like the place in code. But it'd be nice to have a mention somewhere of what this order ends up being for end-user runs.

**Comment by keithamus** [comment]
Hey @JoshuaKGoldberg! I don't think it's mentioned anywhere. I welcome PRs from you or anyone reading this, to add the sort order to the README.

Even better: if you can add a test that verifies the sort order in the README matches the code, or even better than that, an action to generate the sort order in the README. As it's a lot of keys it should be wrapped in a `<details>` element.
