### ISSUE TITLE
sorting scripts fails when switching from `npm-run-all` to `npm-run-all2`

### ISSUE THREAD

**Issue by viceice** [keithamus/sort-package-json#308]
Renovate is now suggesting to replace the `npm-run-all` with `npm-run-all2` which is good, but on some repos `prettier` starts failing.
Any idea?

```diff
diff --git a/package.json b/package.json
index 9090468..58a787e 100644
--- a/package.json
+++ b/package.json
@@ -7,8 +7,8 @@
   "author": "Michael Kriese <michael.kriese@visualon.de>",
   "type": "module",
   "scripts": {
-    "lint": "run-s prettier",
     "postinstall": "husky install",
+    "lint": "run-s prettier",
     "prettier": "prettier \"{**/*,*}.*\" --check --ignore-unknown",
     "prettier:fix": "prettier \"{**/*,*}.*\" --write --ignore-unknown"
   },
```

- https://github.com/containerbase/maven-prebuild/pull/108
- https://github.com/containerbase/base/pull/2044
- https://github.com/bcomnes/npm-run-all2/issues/129

**Comment by viceice** [comment]
Seeing it on yarn v1 and pnpm v8, so seems unrelated to package manager

**Comment by kachkaev** [comment]
Also seeing this in a PR created by Renovate bot. This should be fixed by https://github.com/keithamus/sort-package-json/pull/309.
