### ISSUE TITLE
Convert to ESLint plugin/ Provide an ESLint plugin?

### ISSUE THREAD

**Issue by fisker** [keithamus/sort-package-json#322]
ESLint starting to support other languages. Should we consider?

- [ESLint official JSON plugin](https://github.com/eslint/json)

**Comment by Zamiell** [comment]
The ESLint ecosystem has mostly agreed that formatting should be left to dedicated formatting tools like Prettier. Thus, I think this is best done as a Prettier plugin, which is exactly what [prettier-plugin-packagejson](https://github.com/matzkoh/prettier-plugin-packagejson) does. (It simply calls `sort-package-json` under the hood.)

**Comment by kachkaev** [comment]
I opened https://github.com/eslint/json/issues/37 but maybe this should be done outside `@eslint/json`. Sorting keys via [prettier-plugin-packagejson](https://github.com/matzkoh/prettier-plugin-packagejson) has been working well for me for a few years. The problem with this plugin is that it goes [outside the scope of Prettier](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about):

> **What Prettier is not concerned about**
> Prettier only prints code. It does not transform it. This is to limit the scope of Prettier. Let’s focus on the printing and do it really well!
> Here are a few examples of things that are out of scope for Prettier:
> - ...
> - Sorting/moving imports, object keys, class members, JSX keys, CSS properties or anything else. Apart from being a transform rather than just printing (as mentioned above), sorting is potentially unsafe because of side effects (for imports, as an example) and makes it difficult to verify the most important [correctness](https://prettier.io/docs/en/rationale.html#correctness) goal.

**Comment by mrmckeb** [comment]
We also use the Prettier plugin. I agree that this should not go into ESLint, as people have been moving away from using ESLint for formatting.

**Comment by JoshuaKGoldberg** [comment]
Fun fact, an ESLint plugin for `package.json`s does exist: https://github.com/JoshuaKGoldberg/eslint-plugin-package-json. It has a couple rules around sorting:

* [`package-json/order-properties`](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/7c1f39d7cf8dae2bcc4269f1b4966057bb3d57d2/docs/rules/order-properties.md)
* [`package-json/sort-order`](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/7c1f39d7cf8dae2bcc4269f1b4966057bb3d57d2/docs/rules/sort-collections.md)

`package-json/order-properties` directly uses this package, `sort-package-json`, to determine its ordering. So I think this issue can be closed as already done. 🙂
