### ISSUE TITLE
Maintain indenting level

### ISSUE THREAD

**Issue by G-Rath** [keithamus/sort-package-json#33]
NPM respects the indentation level of `package.json`; if you use 4 spaces for indenting, npm will maintain that, rather than reverting it back to 2 spaces everytime it makes a change to the `package.json`.

Currently it seems `sort-package-json` doesn't respect indentation level, and just instead reverts the `package.json` to 2 spaces.

**Comment by keithamus** [comment]
PRs very welcome 😃
