### ISSUE TITLE
large configs, such as xo should be below dependencies

### ISSUE THREAD

**Issue by forivall** [keithamus/sort-package-json#39]
Given the comment at https://github.com/keithamus/sort-package-json/issues/30#issuecomment-378197067 , I'm curious about why xo was placed above dependencies, given that I have a very large xo config (> 100 lines. I'm not proud of it, but that's besides the point).

In particular, the block of
```
    'browserify',
    'babel',
    'xo',
    'prettier',
    'eslintConfig',
    'eslintIgnore',
    'stylelint',
    'jest',
```

seem like they are all configs that can become very long, and should always be below the dependencies.

**Comment by keithamus** [comment]
Thanks for the issue @forivall.

I mostly added these blocks above dependencies because they are more often hand-edited than the `dependencies`/`devDependencies` fields, and so having them closer to the top means less navigating within the file to edit them.

I am not massively concerned either way. Perhaps itd be good to hear what others think?

**Comment by forivall** [comment]
Yeah, my preference in general is that all of the "official" and generic entries should be above sections that are specific to a third party tool, and aren't related to the core parts of a package.json. Like, it makes sense to put `betterScripts` right next to scripts, but linter and test config aren't really core.

It definitely is a fuzzy classification system though.

**Comment by forivall** [comment]
Yeah, my preference in general is that all of the "official" and generic entries should be above sections that are specific to a third party tool, and aren't related to the core parts of a package.json. Like, it makes sense to put `betterScripts` right next to scripts, but linter and test config aren't really core.

It definitely is a fuzzy classification system though.

**Comment by keithamus** [comment]
my intuition was that it made sense to put these configs next to scripts also - as script invocation can imply parts of the config.

Let's get others involved here, @raphinesse and @jdcrensh may have opinions on this, as well as past contributors like perhaps @bluelovers @selbekk or @simonkberg

**Comment by simonkberg** [comment]
Thanks for the ping. Personally I prefer the ordering as it is today, for the same reasons you already brought up:

> because they are more often hand-edited than the `dependencies`/`devDependencies` fields, and so having them closer to the top means less navigating within the file to edit them.

and 

> my intuition was that it made sense to put these configs next to scripts also - as script invocation can imply parts of the config

Other than that, always having the dependencies defined at the end also means it's easier to navigate _to_ them when needed, instead of trying to find them somewhere in the middle of the file.

**Comment by bluelovers** [comment]
i will like put they low then dependencies & resolutions

**Comment by jdcrensh** [comment]
I'm of the mind to put all config keys between scripts and dependencies. My reasoning is that dependencies should **always** appear at the bottom, which is consistent with nearly all projects I've worked with. It's not that hard to scroll to the end of the file.

**Comment by raphinesse** [comment]
I put the `xo` key next to similar keys. There's nothing more to it. With >100 Lines config, I would probably prefer to have a separate config file though :sweat_smile: 

There's not one size that fits all here. Given that config is out of the picture (https://github.com/keithamus/sort-package-json/issues/30#issuecomment-380425399), I would put everything non-standard at the end. Alphabetically sorted.

**Comment by keithamus** [comment]
So it seems as though we have the following:

 - @forivall, @bluelovers, @raphinesse would vote for these keys below dependencies
 - myself, @simonkberg, @jdcrensh would vote for these keys between scripts and dependencies

I'm not the greatest at maths, but that looks like a tie to me. Nothing so far said has convinced me to move the keys below dependencies, although @jdcrensh's comments about consistently having dependencies at the bottom certainly sways me to put unrecognised non-standard keys higher up.

**Comment by bluelovers** [comment]
oh make this as option let user choose it?

**Comment by keithamus** [comment]
I am not sure this will be resolved any time soon. I'll close this for now. If people have opinions on this please feel free to file a new PR or issue! Thanks
