### ISSUE TITLE
Export sort order to use with npm-package-json-lint

### ISSUE THREAD

**Issue by jogold** [keithamus/sort-package-json#42]
Hi,

It would be great if the sort order of the keys was exported. This way it could be used with `npm-package-json-lint` for the rule `prefer-property-order` (https://github.com/tclindner/npm-package-json-lint/wiki/prefer-property-order)

**Comment by jogold** [comment]
Hi @keithamus, are you planning to publish this soon to npm?

Thanks!

**Comment by keithamus** [comment]
@jogold this should be published, right?

**Comment by jogold** [comment]
@keithamus no it's not:
![image](https://user-images.githubusercontent.com/12623249/46677211-758ca880-cbe2-11e8-8ae6-a3985b920903.png)

**Comment by jogold** [comment]
@keithamus sorry to insist but it's still not published on npm. 

Thanks in advance.

**Comment by keithamus** [comment]
@jogold thanks for reminding me. I've been on vacation for the last week, I'll get this published now.

**Comment by keithamus** [comment]
`1.16.0` is published
