### ISSUE TITLE
Sorting other json files

### ISSUE THREAD

**Issue by artyomsv** [keithamus/sort-package-json#64]
Hi, I know that this library main purpose to sort package.json file, but I'm using it also to sort other json files in my project. I'm not planing to add another similar dependency and wanted to clarify one thing.

I have this json file:
```json
[
  {
    "key": "a",
    "value": "1"
  },
  {
    "key": "b",
    "value": "2"
  }
]
```

and the result of sorting is:

```json
{
  "0": {
    "key": "a",
    "value": "1"
  },
  "1": {
    "key": "b",
    "value": "1"
  }
}
```

Is this transformation behavior is correct or is it a bug?

**Comment by keithamus** [comment]
Yes I'd consider this a bug. I'd happily accept a PR to fix this 😸

**Comment by fisker** [comment]
IMHO: instead of supporting other json file, we should filter files not named `package.json`

**Comment by keithamus** [comment]
I believe this can be closed now. If this is still a bug please feel free to file a PR or another issue!
