### ISSUE TITLE
Ignore subkeys from cli

### ISSUE THREAD

**Issue by anion155** [keithamus/sort-package-json#65]
Would be nice feature if you add ability to ignore some subkeys. I'm using lots scripts dependents on each other, and I want them to be sorted in predefined order like:
```javascript
{
  "scripts": {
    "madge": "madge src/**/*.ts",
    "lint": "tslint --project ./tsconfig.json && npm run madge -- --circular",
    "build": "npm run lint && ttsc",
    "test": "npm run build && nyc --reporter=lcovonly --reporter=text mocha"
  }
}
```

**Comment by fisker** [comment]
@keithamus Is this accepted? If so, I'm going to implement.

**Comment by keithamus** [comment]
I stand firm that I'd like the CLI to always produce the same output. We could look to remove sorting of scripts, or make them more intelligent (like detecting and sortting by scripts that reference each other). 

Thoughts?

**Comment by khitrenovich** [comment]
Being able to ignore sorting of scripts would be nice - in many cases they are sorted by some sort of internal logic (which may not be easy or feasible to automate).

**Comment by anion155** [comment]
> I stand firm that I'd like the CLI to always produce the same output. We could look to remove sorting of scripts, or make them more intelligent (like detecting and sortting by scripts that reference each other).
> 
> Thoughts?

For this we would need to at least support

**Comment by anion155** [comment]
Sorry, mispressed ))

**Comment by anion155** [comment]
> I stand firm that I'd like the CLI to always produce the same output. We could look to remove sorting of scripts, or make them more intelligent (like detecting and sortting by scripts that reference each other).
> 
> Thoughts?

It could be other fields in pkg.json that would need to excluded from sorting, maybe readed by 3-rd party modules. But special logic for `scripts` would be cool.

**Comment by khitrenovich** [comment]
> @anion155 closed this as [completed](https://github.com/keithamus/sort-package-json/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [8 hours ago](https://github.com/keithamus/sort-package-json/issues/65#event-11376133038)

I don't think it was implemented... unless I'm missing something!

**Comment by anion155** [comment]
> I don't think it was implemented... unless I'm missing something!
Issue is 5 years sits in my "issues list" without any updates. I don't care already. If you do 'reopen', please

**Comment by khitrenovich** [comment]
> > I don't think it was implemented... unless I'm missing something!
> 
> Issue is 5 years sits in my "issues list" without any updates. I don't care already. If you do 'reopen', please

No, I don't care enough either - just would expect this to be "closed as not planned" rather than "... as completed" in this case.
