### ISSUE TITLE
enabling sorting of `type` field

### ISSUE THREAD

**Issue by eankeen** [keithamus/sort-package-json#76]
especially since the latest versions of node support the [`type`] field for cool esm interop, i think it would be good to add that sorting for that term. i personally would like to have it above the `main` field, but someone should chime in if they have a better location.

if this is a good idea, i can make a pr

[`type`]: https://nodejs.org/api/esm.html#esm_code_package_json_code_code_type_code_field

**Comment by keithamus** [comment]
Yes! PR's very much welcome 👌

**Comment by eankeen** [comment]
@keithamus just made a pr, how does it look?

**Comment by keithamus** [comment]
https://github.com/keithamus/sort-package-json/releases/tag/v1.24.0 has been released. Thanks @eankeen!
