### ISSUE TITLE
Opt-out of sorting keywords

### ISSUE THREAD

**Issue by robatwilliams** [keithamus/sort-package-json#83]
The order of `keywords` is preserved when displayed on npmjs.com.

Packages may wish to order keywords such that related ones are together. For example: what it does, what tech it's for, what tech it uses, other related packages.

**Comment by keithamus** [comment]
You raise a good point. Let's just unilaterally disable the sorting of keywords. PRs welcome!

**Comment by niksy** [comment]
Sorry for commenting on closed issue, but is there a possibility to sort keywords alphabetically, or some sort function we can use to modify sorting method just for keywords?

**Comment by keithamus** [comment]
Hey @niksy! You can create a fork of this repository and change it, perhaps publish it as `sort-package-json-and-keywords`?

**Comment by niksy** [comment]
@keithamus thanks!
