### ISSUE TITLE
Sorting of "exports" field

### ISSUE THREAD

**Issue by RebeccaStevens** [keithamus/sort-package-json#84]
Conditional Exports:
https://nodejs.org/api/esm.html#esm_conditional_exports

Related to #76

Personally I would like to have this be sorted directly after "main" as it essentially replaces fields like "module", "browser" etc.

**Comment by keithamus** [comment]
Sounds like a good idea. PRs welcome!

**Comment by fisker** [comment]
@RebeccaStevens check this comment https://github.com/keithamus/sort-package-json/pull/88#issuecomment-560997003
