### ISSUE TITLE
keywords is not sorted

### ISSUE THREAD

**Issue by matzkoh** [keithamus/sort-package-json#99]
on v1.31.0

input

```
  "keywords": [
    "C",
    "C",
    "B",
    "A"
  ]
```

actual

```
  "keywords": [
    "C",
    "B",
    "A"
  ]
```

expected

```
  "keywords": [
    "A",
    "B",
    "C"
  ]
```

**Comment by keithamus** [comment]
This is intended. See https://github.com/keithamus/sort-package-json/issues/83: 

> Packages may wish to order keywords such that related ones are together. For example: what it does, what tech it's for, what tech it uses, other related packages.
